pub const MAX_CASCADES: usize = 6;
pub const TOTAL_BINDINGS: usize = 1 + MAX_CASCADES * 4;

#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct OceanSettingsUniform {
    pub deep_color: [f32; 4],
    pub shallow_color: [f32; 4],
    pub sss_color: [f32; 4],
    pub caustic_color_tint: [f32; 4],
    pub sun_color: [f32; 4],
    pub sky_color_day_zenith: [f32; 4],
    pub sky_color_day_horizon: [f32; 4],
    pub sky_color_night_zenith: [f32; 4],
    pub sky_color_night_horizon: [f32; 4],
    pub sky_color_sunset_orange: [f32; 4],
    pub sky_color_sunset_pink: [f32; 4],
    pub sky_color_horizon_glow: [f32; 4],
    pub moon_color_lit: [f32; 4],
    pub moon_color_dark: [f32; 4],
    pub cloud_color_night: [f32; 4],
    pub cloud_color_day: [f32; 4],
    pub wind_vector: [f32; 2],
    pub _pad_vec2: [f32; 2],
    pub moon_phase_offset: [f32; 3],
    pub _pad_moon: f32,
    pub mesh_size: f32,
    pub time_scale: f32,
    pub chop_scale: f32,
    pub amplitude_scale: f32,
    pub l_small: f32,
    pub max_w: f32,
    pub fovy: f32,
    pub zfar: f32,
    pub cam_speed: f32,
    pub cam_boost: f32,
    pub cam_sensitivity: f32,
    pub roughness: f32,
    pub f_0: f32,
    pub specular_scale: f32,
    pub reflection_scale: f32,
    pub foam_scale: f32,
    pub sss_distortion_scale: f32,
    pub caustic_scale: f32,
    pub caustic_size: f32,
    pub caustic_speed: f32,
    pub caustic_intensity: f32,
    pub caustic_depth: f32,
    pub caustic_max_distance: f32,
    pub micro_normal_strength: f32,
    pub foam_threshold: f32,
    pub foam_speed: f32,
    pub foam_roughness: f32,
    pub daynight_cycle: f32,
    pub sun_offset_z: f32,
    pub sun_size_inner: f32,
    pub sun_size_outer: f32,
    pub sun_halo_power: f32,
    pub moon_radius: f32,
    pub moon_dist: f32,
    pub moon_crater_scale: f32,
    pub moon_halo_power: f32,
    pub star_count: f32,
    pub star_threshold: f32,
    pub star_blink_speed: f32,
    pub cloud_speed: f32,
    pub cloud_density_low: f32,
    pub cloud_density_high: f32,
    pub mesh_subdivisions: u32,
    pub fft_subdivisions: u32,
    pub pass_num: u32,
    pub ocean_seed: u32,
    pub caustic_octaves: u32,
    pub star_size: f32,
    pub aurora_strength: f32,
    pub _pad_b_align: [f32; 3],
    pub pad_b: [u32; 4],
    pub cascade_data: [[f32; 4]; MAX_CASCADES],
    pub cascade_count: u32,
    pub _pad_cascade: [u32; 3],
    pub sunset_scatter_color: [f32; 3],
    pub sunset_scatter_intensity: f32,
    pub foam_base_color: [f32; 3],
    pub sss_min_height: f32,
    pub sss_max_height: f32,
    pub sss_power: f32,
    pub sss_intensity: f32,
    pub detail_fade: f32,
    pub ambient_scale: f32,
    pub blend_strength: f32,
    pub bloom_scale: f32,
    pub reflection_min: f32,
    pub reflection_max: f32,
    pub moon_light_dim: f32,
    pub sky_zenith_gradient_exp: f32,
    pub horizon_glow_mult: f32,
    pub sunset_orange_weight: f32,
    pub sunset_intensity: f32,
    pub sun_halo_intensity: f32,
    pub moon_halo_intensity: f32,
    pub micro_uv_freq: f32,
    pub micro_time_freq: f32,
    pub micro_strength_mod: f32,
    pub foam_crest_width: f32,
    pub caustic_aberration: f32,
    pub caustic_smooth_low: f32,
    pub caustic_smooth_high: f32,
    pub aurora_brightness: f32,
    pub aurora_y_threshold: f32,
    pub water_brightness_mod: f32,
    pub decay_factor: f32,
    pub dissipation_factor: f32,
    pub warp_uv_scale: f32,
    pub warp_strength: f32,
    pub warp_time_scale: f32,
    pub foam_octaves: u32,
    pub foam_power: f32,
    pub hash_scale: f32,
    pub hash_dot: f32,
    pub steepness_threshold_low: f32,
    pub steepness_threshold_high: f32,
    pub y_displacement_weight: f32,
    pub wave_epsilon: f32,
    pub wave_height_exp: f32,
    pub wave_height_sharp: f32,
    pub night_water_floor: f32,
    pub fresnel_sky_cap: f32,
    pub caustic_sss_blend: f32,
    pub _pad_final: [f32; 12],
}
